#!/usr/bin/env bash
#parsing dig output

get_dns_info() {
    local subdomain=$1
    local domain=$2
    local conc

    if [ -z "$subdomain" ]; then
        conc="$domain"
        subdomain="$domain"
    else
        conc="$subdomain.$domain"
    fi

    dig "$conc" | grep -A1 'ANSWER SECTION:' | awk -v subdomain="$subdomain" '
    /IN/ {
        record_type = $4
        destination = $5
        print "The subdomain " subdomain " is a " record_type " record and points to " destination
    }'
}

domain=$1
subdomain=$2


if [ -z "$subdomain" ]; then
    get_dns_info "" "$domain"
    default_subdomains=("www" "lb-01" "web-01" "web-02")
    for sub in "${default_subdomains[@]}"; do
        get_dns_info "$sub" "$domain"
    done
else
    get_dns_info "$subdomain" "$domain"
fi
