#!/usr/bin/env bash
# okey lwt's install nginx and configure it
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
