#!/usr/bin/env bash
# okey lwt's install nginx and configure it
sudo apt update
sudo apt -y install nginx
sudo service nginx start
sudo chmod -R 775 /var/www/html
sudo echo "Hello World!" > /var/www/html/index.html
sudo nginx -s reload
