#!/usr/bin/env bash
# okey lwt's install nginx and configure it
sudo apt update
sudo apt -y install nginx
sudo ufw allow "Nginx HTTP"
sudo service nginx start
sudo chmod -R 775 /var/www/html
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo sed -i "#location \/#i \tlocation /redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}" /etc/nginx/sites-available/default
sudo nginx -s reload
