#!/usr/bin/env bash
# okey lwt's install nginx and configure it
sudo apt update
sudo apt -y install nginx
sudo ufw allow "Nginx HTTP"
sudo service nginx start
sudo chmod -R 775 /var/www/html
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
sudo sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
sudo nginx -s reload
