#!/usr/bin/env bash
# configure HAproxy load balancer

sudo apt update -y -qq
sudo apt install haproxy -y -qq
sudo chown -R "$USER":"$USER" /etc/haproxy/
sudo chmod -R 755 /etc/haproxy
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup
confi=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend view
    bind *:80
    default_backend Oxshady-backend

backend Oxshady-backend
    balance roundrobin
    server 465043-web-01 52.201.152.150:80 check
    server 465043-web-02 18.209.152.20:80 check
"
# shellcheck disable=SC2154
echo "$confi" | sudo dd status=none of=/etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy
if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi
