#!/usr/bin/env bash
# configure HAproxy load balancer
sudo apt update -y -qq
sudo apt install haproxy -y -qq
sudo chown -R "$USER":"$USER" /etc/haproxy/
sudo chmod -R 755 /etc/haproxy
echo "frontend myproxy
	bind *:80
	mode http
	default_backend myservers
backend myservers
	balance roundrobin
	mode http
	server 465043-web-01 52.201.152.150:80 check
	server 465043-web-02 18.209.152.20:80 check
ENABLED=1
" >> /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy
sudo systemctl enable haproxy
