#!/usr/bin/env bash
# listen to port 80
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
