#!/bin/bash
# debbug server to make it listen to port 8- successfullt

nginx_config="/etc/nginx/sites-available/default"
if ! grep -q "listen 80;" "/etc/nginx/sites-available/default"; then
    echo "listen 80;" | sudo tee -a "/etc/nginx/sites-available/default" > /dev/null
fi
sudo systemctl restart nginx
