#!/usr/bin/env bash
# script that displays To infinity and beyond indefinitely In between each iteration of the loop, add a sleep 2 I am invincible!!! when receiving a SIGTERM signal
handle_signal(){
	echo "I am invincible!!!"
}
trap 'handle_signal' SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2shel
done
