#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes
i=0
while [ "$i" -le 12 ]
do
	echo "Hour: $i"
	x=1
	while [ "$x" -le 59 ]
	do
		echo "$x"
		((x+=1))
	done
	((i+=1))
done
