#!/usr/bin/env bash
# ufw configuration
sudo apt update -y && sudo apt upgrade -y
sudo apt install ufw -y
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh/tcp
sudo ufw allow https/tcp
sudo ufw allow http/tcp
sudo ufw enable

